INSERT INTO cryptos (symbol, name, url) VALUES
('BTC/USD', 'Bitcoin', 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png'),
('ETH/USD', 'Ethereum', 'https://assets.coingecko.com/coins/images/279/small/ethereum.png'),
('USDT/USD', 'Tether', 'https://assets.coingecko.com/coins/images/325/small/Tether-logo.png'),
('USDC/USD', 'USD Coin', 'https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png'),
('BNB/USD', 'BNB', 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png'),
('SOL/USD', 'Solana', 'https://assets.coingecko.com/coins/images/4128/small/solana.png'),
('XRP/USD', 'XRP', 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png'),
('ADA/USD', 'Cardano', 'https://assets.coingecko.com/coins/images/975/small/cardano.png'),
('DOGE/USD', 'Dogecoin', 'https://assets.coingecko.com/coins/images/5/small/dogecoin.png'),
('DOT/USD', 'Polkadot', 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png'),
('TRX/USD', 'TRON', 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png'),
('POL/USD', 'Polygon', 'https://assets.coingecko.com/coins/images/4713/small/polygon.png'),
('LTC/USD', 'Litecoin', 'https://assets.coingecko.com/coins/images/2/small/litecoin.png'),
('BCH/USD', 'Bitcoin Cash', 'https://assets.coingecko.com/coins/images/780/small/bitcoin-cash-circle.png'),
('AVAX/USD', 'Avalanche', 'https://assets.coingecko.com/coins/images/12559/small/coin-round-red.png'),
('UNI/USD', 'Uniswap', 'https://assets.coingecko.com/coins/images/12504/small/uniswap-uni.png'),
('LINK/USD', 'Chainlink', 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png'),
('XLM/USD', 'Stellar', 'https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png'),
('ATOM/USD', 'Cosmos Hub', 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png'),
('AAVE/USD', 'Aave', 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png');